# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Elabud - Timeless preserved flowers for any occasion">
    <title>Elabud | Preserved Flowers</title>
    <style>
        /* General Reset */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: Arial, sans-serif;
        }
        body {
            line-height: 1.6;
            color: #333;
            background-color: #fafafa;
        }

        /* Header */
        header {
            background-color: #e8b4b8;
            color: #fff;
            padding: 1rem 2rem;
            text-align: center;
        }
        header h1 {
            font-size: 2.5rem;
            font-weight: bold;
            letter-spacing: 2px;
        }

        /* Navigation */
        nav {
            display: flex;
            justify-content: center;
            background-color: #fff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        nav ul {
            list-style: none;
            display: flex;
        }
        nav ul li {
            margin: 0 1rem;
        }
        nav ul li a {
            text-decoration: none;
            color: #e8b4b8;
            font-size: 1.1rem;
            font-weight: bold;
        }
        nav ul li a:hover {
            color: #b87b7f;
        }

        /* Hero Section */
        .hero {
            text-align: center;
            padding: 4rem 2rem;
            background: url('https://images.unsplash.com/photo-1519682337058-a94d519337bc') no-repeat center center/cover;
            color: #fff;
            position: relative;
        }
        .hero h2 {
            font-size: 3rem;
            margin-bottom: 1rem;
        }
        .hero p {
            font-size: 1.2rem;
        }
        .hero::after {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.4);
            z-index: 1;
        }
        .hero * {
            position: relative;
            z-index: 2;
        }

        /* Products Section */
        .products {
            padding: 2rem;
            text-align: center;
        }
        .products h2 {
            font-size: 2.5rem;
            margin-bottom: 1.5rem;
            color: #b87b7f;
        }
        .product-list {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
        }
        .product {
            margin: 1rem;
            background: #fff;
            border: 1px solid #ddd;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            width: 250px;
            text-align: left;
        }
        .product img {
            width: 100%;
            height: 200px;
            object-fit: cover;
        }
        .product h3 {
            margin: 1rem;
            font-size: 1.5rem;
        }
        .product p {
            margin: 0 1rem 1rem;
        }

        /* Contact Section */
        .contact {
            background-color: #f8e9eb;
            padding: 2rem;
            text-align: center;
        }
        .contact h2 {
            font-size: 2.5rem;
            margin-bottom: 1rem;
            color: #b87b7f;
        }
        .contact p {
            font-size: 1.2rem;
        }

        /* Footer */
        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 1rem 0;
            margin-top: 2rem;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <header>
        <h1>Elabud</h1>
        <p>Timeless Preserved Flowers</p>
    </header>

    <!-- Navigation -->
    <nav>
        <ul>
            <li><a href="#home">Home</a></li>
            <li><a href="#products">Products</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </nav>

    <!-- Hero Section -->
    <section class="hero" id="home">
        <h2>Blooms That Last Forever</h2>
        <p>Discover elegant preserved flowers that stay beautiful for years.</p>
    </section>

    <!-- Products Section -->
    <section class="products" id="products">
        <h2>Our Collection</h2>
        <div class="product-list">
            <div class="product">
                <img src="https://images.unsplash.com/photo-1505744386214-51f8cf6c8f09" alt="Pink Rose Box">
                <h3>Pink Rose Box</h3>
                <p>A stunning arrangement of preserved pink roses.</p>
            </div>
            <div class="product">
                <img src="https://images.unsplash.com/photo-1517649763962-0c623066013b" alt="Luxury Rose Dome">
                <h3>Luxury Rose Dome</h3>
                <p>Timeless roses beautifully displayed under glass.</p>
            </div>
            <div class="product">
                <img src="https://images.unsplash.com/photo-1526772662000-3f88f10405ff" alt="Mixed Floral Wreath">
                <h3>Floral Wreath</h3>
                <p>Preserved flowers crafted into a decorative wreath.</p>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section class="contact" id="contact">
        <h2>Contact Us</h2>
        <p>Have questions? Reach out to us at <strong>contact@elabud.com</strong>.</p>
    </section>

    <!-- Footer -->
    <footer>
        <p>&copy; 2024 Elabud | All Rights Reserved</p>
    </footer>
</body>
</html>
